import type {
  AdminAlertRecord,
  ChatMessageRecord,
  ChatThreadRecord,
  AdminUserRecord,
  ContentBlockRecord,
  DestinationOptionRecord,
  FAQRecord,
  StudyAbroadRecord,
  TestimonialRecord,
  TourPackageRecord,
  VisaServiceRecord,
} from "./adminTypes";
import type { ServicePricingRecord } from "./types";

const now = "2026-03-30T08:00:00.000Z";

export const DEFAULT_ADMIN_USERS: AdminUserRecord[] = [];

export const DEFAULT_VISA_SERVICES: VisaServiceRecord[] = [
  {
    id: "visa-service-uk",
    country: "United Kingdom",
    title: "UK Visitor Visa Support",
    requirements: "Passport, bank statement, employment or sponsor documents, and travel itinerary.",
    checklistContent: "Passport bio page, financial proof, accommodation plan, and covering letter.",
    pricingNote: "Fees vary depending on the urgency and application type.",
    seoTitle: "UK Visitor Visa Support | GenieHub",
    seoDescription: "Get guided support for UK visitor visa applications from Ghana.",
    ctaEnabled: true,
    status: "published",
    updatedAt: now,
  },
];

export const DEFAULT_STUDY_ABROAD_RECORDS: StudyAbroadRecord[] = [
  {
    id: "study-canada",
    country: "Canada",
    title: "Canada Study Pathways",
    programmes: "Diploma, undergraduate, postgraduate, and professional programmes.",
    intakeInfo: "January, May, and September intakes depending on school.",
    content: "Support your clients with school selection, admission review, SOP preparation, and visa readiness.",
    ctaBanner: "Book a study consultation",
    status: "published",
    updatedAt: now,
  },
];

export const DEFAULT_TOUR_PACKAGES: TourPackageRecord[] = [
  {
    id: "tour-dubai-escape",
    title: "Dubai Escape",
    destination: "Dubai",
    duration: "5 days / 4 nights",
    description: "A premium city break with shopping, desert experiences, and flexible hotel upgrades.",
    startingPrice: "From GHS 15,000",
    currency: "GHS",
    travelPeriod: "June to September 2026",
    travelDates: "12 Aug 2026 - 17 Aug 2026",
    itinerarySummary: "City tour, desert experience, shopping, and flexible hotel upgrades.",
    inclusions: "Hotel, airport transfers, city tour, selected activities.",
    exclusions: "Visa fee, meals not stated, travel insurance, personal spending.",
    imageGallery: [],
    featured: true,
    visible: true,
    status: "published",
    updatedAt: now,
  },
];

export const DEFAULT_DESTINATION_OPTIONS: DestinationOptionRecord[] = [
  {
    id: "destination-uk",
    name: "United Kingdom",
    category: "study-abroad",
    active: true,
    updatedAt: now,
  },
  {
    id: "destination-canada",
    name: "Canada",
    category: "study-abroad",
    active: true,
    updatedAt: now,
  },
  {
    id: "destination-dubai",
    name: "Dubai",
    category: "tour",
    active: true,
    updatedAt: now,
  },
  {
    id: "destination-cape-coast",
    name: "Cape Coast & Elmina",
    category: "tour",
    active: true,
    updatedAt: now,
  },
  {
    id: "destination-mole",
    name: "Mole National Park",
    category: "tour",
    active: true,
    updatedAt: now,
  },
  {
    id: "destination-london",
    name: "London",
    category: "travel",
    active: true,
    updatedAt: now,
  },
  {
    id: "destination-new-york",
    name: "New York",
    category: "travel",
    active: true,
    updatedAt: now,
  },
  {
    id: "destination-uk-visa",
    name: "United Kingdom",
    category: "visa",
    active: true,
    updatedAt: now,
  },
];

export const DEFAULT_TESTIMONIALS: TestimonialRecord[] = [
  {
    id: "testimonial-1",
    name: "Efua A.",
    quote: "GenieHub kept me informed at every step and made my visa process feel manageable.",
    category: "visa",
    featured: true,
    displayOrder: 1,
    status: "approved",
    updatedAt: now,
  },
];

export const DEFAULT_FAQS: FAQRecord[] = [
  {
    id: "faq-visa-processing",
    question: "How long does visa processing usually take?",
    answer: "Timelines depend on destination and season, but GenieHub updates clients as soon as requirements or embassy stages change.",
    category: "visa",
    displayOrder: 1,
    published: true,
    updatedAt: now,
  },
];

export const DEFAULT_CONTENT_BLOCKS: ContentBlockRecord[] = [
  {
    id: "content-nav-home",
    key: "header_navigation.home",
    sectionKey: "header_navigation",
    title: "Home",
    description: "Main navigation link",
    content: "/",
    ctaHref: "/",
    displayOrder: 1,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-nav-about",
    key: "header_navigation.about",
    sectionKey: "header_navigation",
    title: "About",
    description: "Main navigation link",
    content: "/about",
    ctaHref: "/about",
    displayOrder: 2,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-nav-services",
    key: "header_navigation.services",
    sectionKey: "header_navigation",
    title: "Services",
    description: "Main navigation link",
    content: "/services",
    ctaHref: "/services",
    displayOrder: 3,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-nav-study",
    key: "header_navigation.study_abroad",
    sectionKey: "header_navigation",
    title: "Study Abroad",
    description: "Main navigation link",
    content: "/study-abroad",
    ctaHref: "/study-abroad",
    displayOrder: 4,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-nav-visa",
    key: "header_navigation.visa_help",
    sectionKey: "header_navigation",
    title: "Visa Help",
    description: "Main navigation link",
    content: "/visa-assistance",
    ctaHref: "/visa-assistance",
    displayOrder: 5,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-nav-tours",
    key: "header_navigation.tours",
    sectionKey: "header_navigation",
    title: "Tours",
    description: "Main navigation link",
    content: "/tours",
    ctaHref: "/tours",
    displayOrder: 6,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-nav-blog",
    key: "header_navigation.blog",
    sectionKey: "header_navigation",
    title: "Blog",
    description: "Main navigation link",
    content: "/blog",
    ctaHref: "/blog",
    displayOrder: 7,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-nav-contact",
    key: "header_navigation.contact",
    sectionKey: "header_navigation",
    title: "Contact",
    description: "Main navigation link",
    content: "/contact",
    ctaHref: "/contact",
    displayOrder: 8,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-services-study-abroad",
    key: "homepage_services.study_abroad",
    sectionKey: "homepage_services",
    title: "Study Abroad",
    description: "Full support from school selection to visa approval. UK, Canada, USA, Australia and more.",
    content: "/study-abroad",
    icon: "GraduationCap",
    displayOrder: 1,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-services-visa",
    key: "homepage_services.visa_assistance",
    sectionKey: "homepage_services",
    title: "Visa Assistance",
    description: "Student, tourist, work and business visa processing with expert document guidance.",
    content: "/visa-assistance",
    icon: "FileText",
    displayOrder: 2,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-services-tours",
    key: "homepage_services.tour_packages",
    sectionKey: "homepage_services",
    title: "Tour Packages",
    description: "Curated local and international tour experiences. Cape Coast, Dubai, Turkey and beyond.",
    content: "/tours",
    icon: "Map",
    displayOrder: 3,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-hero-action-primary",
    key: "homepage_hero_actions.primary",
    sectionKey: "homepage_hero_actions",
    title: "Create Client Account",
    description: "Primary hero CTA",
    content: "/signup",
    ctaLabel: "Create Client Account",
    ctaHref: "/signup",
    displayOrder: 1,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-hero-action-secondary",
    key: "homepage_hero_actions.secondary",
    sectionKey: "homepage_hero_actions",
    title: "Explore Services",
    description: "Secondary hero CTA",
    content: "/services",
    ctaLabel: "Explore Services",
    ctaHref: "/services",
    displayOrder: 2,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-process-step-1",
    key: "why_choose_us.step_1",
    sectionKey: "why_choose_us",
    title: "Tell Us Your Goal",
    description: "Book a consultation and share your travel or study plans with our team.",
    content: "Step 1",
    icon: "MessageSquare",
    displayOrder: 1,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-study-support-1",
    key: "study_abroad_support.university_selection",
    sectionKey: "study_abroad_support",
    title: "University & programme selection",
    content: "University & programme selection",
    displayOrder: 1,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-study-support-2",
    key: "study_abroad_support.application_support",
    sectionKey: "study_abroad_support",
    title: "Application & personal statement support",
    content: "Application & personal statement support",
    displayOrder: 2,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-study-support-3",
    key: "study_abroad_support.scholarship_guidance",
    sectionKey: "study_abroad_support",
    title: "Scholarship search & guidance",
    content: "Scholarship search & guidance",
    displayOrder: 3,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-study-support-4",
    key: "study_abroad_support.document_prep",
    sectionKey: "study_abroad_support",
    title: "Document preparation & verification",
    content: "Document preparation & verification",
    displayOrder: 4,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-study-support-5",
    key: "study_abroad_support.visa_prep",
    sectionKey: "study_abroad_support",
    title: "Visa application & interview prep",
    content: "Visa application & interview prep",
    displayOrder: 5,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-study-support-6",
    key: "study_abroad_support.pre_departure",
    sectionKey: "study_abroad_support",
    title: "Pre-departure orientation",
    content: "Pre-departure orientation",
    displayOrder: 6,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-study-support-7",
    key: "study_abroad_support.accommodation",
    sectionKey: "study_abroad_support",
    title: "Accommodation guidance",
    content: "Accommodation guidance",
    displayOrder: 7,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-study-support-8",
    key: "study_abroad_support.post_arrival",
    sectionKey: "study_abroad_support",
    title: "Post-arrival support",
    content: "Post-arrival support",
    displayOrder: 8,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-process-step-2",
    key: "why_choose_us.step_2",
    sectionKey: "why_choose_us",
    title: "We Review & Advise",
    description: "Our experts assess your eligibility, gather documents, and prepare your application.",
    content: "Step 2",
    icon: "FileSearch",
    displayOrder: 2,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-process-step-3",
    key: "why_choose_us.step_3",
    sectionKey: "why_choose_us",
    title: "We Submit & Follow Up",
    description: "We handle submissions, track progress, and keep you informed every step of the way.",
    content: "Step 3",
    icon: "Send",
    displayOrder: 3,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-process-step-4",
    key: "why_choose_us.step_4",
    sectionKey: "why_choose_us",
    title: "You Travel",
    description: "Get your approval, pack your bags, and start your journey with confidence.",
    content: "Step 4",
    icon: "CheckCircle",
    displayOrder: 4,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-trust-1",
    key: "trust_points.client_tracking",
    sectionKey: "trust_points",
    title: "Secure client workspace",
    description: "Keep applications, documents, and updates in one guided space.",
    content: "Secure client workspace",
    icon: "Shield",
    displayOrder: 1,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-trust-2",
    key: "trust_points.ops_visibility",
    sectionKey: "trust_points",
    title: "Bookings, tracking, and uploads in one place",
    description: "A practical flow for clients and staff without confusion.",
    content: "Bookings, tracking, and uploads in one place",
    icon: "Globe",
    displayOrder: 2,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-highlight-1",
    key: "service_highlights.fast_follow_up",
    sectionKey: "service_highlights",
    title: "Fast follow-up",
    description: "Clear updates and guided next steps keep clients confident.",
    content: "Fast follow-up",
    icon: "Sparkles",
    displayOrder: 1,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-highlight-2",
    key: "service_highlights.document_support",
    sectionKey: "service_highlights",
    title: "Document support",
    description: "Get practical guidance on what to upload and what still needs work.",
    content: "Document support",
    icon: "Files",
    displayOrder: 2,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-highlight-3",
    key: "service_highlights.travel_planning",
    sectionKey: "service_highlights",
    title: "Travel planning",
    description: "Consultations, tours, and support services managed from one rhythm.",
    content: "Travel planning",
    icon: "Plane",
    displayOrder: 3,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-footer-quick-study",
    key: "footer_quick_links.study_abroad",
    sectionKey: "footer_quick_links",
    title: "Study Abroad",
    content: "/study-abroad",
    ctaHref: "/study-abroad",
    displayOrder: 1,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-footer-quick-visa",
    key: "footer_quick_links.visa_assistance",
    sectionKey: "footer_quick_links",
    title: "Visa Assistance",
    content: "/visa-assistance",
    ctaHref: "/visa-assistance",
    displayOrder: 2,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-footer-quick-tours",
    key: "footer_quick_links.tour_packages",
    sectionKey: "footer_quick_links",
    title: "Tour Packages",
    content: "/tours",
    ctaHref: "/tours",
    displayOrder: 3,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-footer-support-faq",
    key: "footer_support_links.faq",
    sectionKey: "footer_support_links",
    title: "FAQ",
    content: "/faq",
    ctaHref: "/faq",
    displayOrder: 1,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-footer-support-blog",
    key: "footer_support_links.blog",
    sectionKey: "footer_support_links",
    title: "Blog",
    content: "/blog",
    ctaHref: "/blog",
    displayOrder: 2,
    visible: true,
    published: true,
    updatedAt: now,
  },
  {
    id: "content-footer-support-contact",
    key: "footer_support_links.contact",
    sectionKey: "footer_support_links",
    title: "Contact Us",
    content: "/contact",
    ctaHref: "/contact",
    displayOrder: 3,
    visible: true,
    published: true,
    updatedAt: now,
  },
];

export const DEFAULT_SERVICE_PRICING: ServicePricingRecord[] = [
  {
    id: "pricing-consultation",
    name: "Consultation",
    description: "One-on-one travel or visa consultation.",
    price: 500,
    currency: "GHS",
    category: "consultation",
    visible: true,
    displayOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pricing-sop",
    name: "SOP Assistance",
    description: "Guided support for personal statements and SOP writing.",
    price: 300,
    currency: "GHS",
    category: "document-support",
    visible: true,
    displayOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pricing-visa",
    name: "Visa Support",
    description: "Application guidance, checklist review, and process support.",
    price: 650,
    currency: "GHS",
    category: "visa",
    visible: true,
    displayOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
];

export const DEFAULT_CHAT_THREADS: ChatThreadRecord[] = [];

export const DEFAULT_CHAT_MESSAGES: ChatMessageRecord[] = [];

export const DEFAULT_ADMIN_ALERTS: AdminAlertRecord[] = [];
